# Generated by Django 3.0.6 on 2020-05-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art2Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('curator', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('exhibition', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'artron',
            },
        ),
        migrations.CreateModel(
            name='Art3Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('curator', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '99ys',
            },
        ),
        migrations.CreateModel(
            name='ArtItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('curator', models.CharField(max_length=255)),
                ('exhibition', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'artlinkart',
            },
        ),
    ]
